---
# Source: helm for kubernetes/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bootong
  labels:
    app: bootong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bootong
  template:
    metadata:
      labels:
        app: bootong
    spec:
      containers:
        - name: bootong
          image: docker.io/phengbunath/bootong:1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
